Repository DeKal/portfolio-next-js, pull requests merged in 2019-12, with the labels that each got.

#24 Add Footer
  pages/index.js
  public/fonts/ip/LICENSE.txt
  public/fonts/ip/README.txt
  public/fonts/ip/config.json
  public/fonts/ip/css/animation.css
  public/fonts/ip/css/ip-codes.css
  public/fonts/ip/css/ip-embedded.css
  public/fonts/ip/css/ip-ie7-codes.css
  public/fonts/ip/css/ip-ie7.css
  public/fonts/ip/css/ip.css
  public/fonts/ip/demo.html
  public/fonts/ip/font/ip.eot
  public/fonts/ip/font/ip.svg
  public/fonts/ip/font/ip.ttf
  public/fonts/ip/font/ip.woff
  public/fonts/ip/font/ip.woff2
  styles/blocks/footer.sass
  styles/globalStyle.sass
  styles/helpers/base.sass
  styles/helpers/fonts.sass
  views/components/Footer.js
  views/components/__test__/Footer.spec.tsx
  views/components/__test__/__snapshots__/Footer.spec.tsx.snap
  views/components/common/Icon.js
  views/components/footer/GoTop.js
  views/theme.js
Labels: enhancement

#26 Add Scrutinizer config
  .scrutinizer.yml
  README.md
  jest.config.js
Labels: enhancement

#23 Adding Home page
  pages/index.js
  public/images/bg.jpg
  styles/blocks/home.sass
  styles/globalStyle.sass
  views/components/Home.js
  views/components/__test__/Home.spec.tsx
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
  views/theme.js
  yarn.lock
Labels: enhancement

#22 Add About Page
  pages/index.js
  public/translations/en.json
  public/translations/vn.json
  styles/blocks/about.sass
  styles/helpers/variables.sass
  views/components/About.js
  views/components/Footer.js
  views/components/__test__/About.spec.tsx
  views/components/__test__/__snapshots__/About.spec.tsx.snap
  views/components/__test__/__snapshots__/Footer.spec.tsx.snap
  views/components/about/CardHeader.js
  views/components/about/CardInfo.js
  views/components/about/__test__/CardHeader.spec.tsx
  views/components/about/__test__/CardInfo.spec.tsx
  views/components/about/__test__/__snapshots__/CardHeader.spec.tsx.snap
  views/components/about/__test__/__snapshots__/CardInfo.spec.tsx.snap
  views/theme.js
Labels: enhancement

#28 Add Contact Component
  pages/index.js
  portfolio.code-workspace
  public/images/bg-pattern.jpg
  public/images/map.jpg
  public/translations/en.json
  public/translations/vn.json
  styles/blocks/contacts.sass
  styles/globalStyle.sass
  styles/helpers/base.sass
  utils/withThemeProviders.js
  views/components/Contact.js
  views/components/__test__/Contact.spec.tsx
  views/components/__test__/__snapshots__/Contact.spec.tsx.snap
  views/components/__test__/__snapshots__/Footer.spec.tsx.snap
  views/components/common/Icon.js
  views/components/contact/Content.js
  views/components/contact/Description.js
  views/components/contact/Header.js
  views/components/contact/Info.js
  views/components/contact/Logo.js
  views/components/contact/Map.js
  views/components/contact/Socials.js
  views/theme.js
Labels: enhancement

#38 Fix bug Home components doesn't have id to navigate to #37
  views/components/Home.js
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
Labels: bug

#39 Change language home
  public/translations/en.json
  public/translations/vn.json
  views/components/Home.js
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
Labels: enhancement

#40 Add favicon
  public/favicon.ico
Labels: enhancement

#41 Split Experiences and Why me into 2 components
  pages/index.js
  views/components/Experiences.js
  views/components/WhyMe.js
Labels: enhancement

#46 Add Why Me Page
  consts/pages.js
  pages/index.js
  public/translations/en.json
  public/translations/vn.json
  styles/blocks/services.sass
  views/components/WhyMe.js
  views/components/__test__/WhyMe.spec.tsx
  views/components/__test__/__snapshots__/WhyMe.spec.tsx.snap
  views/components/whyme/Quote.js
  views/components/whyme/Title.js
Labels: enhancement

#48 Add exp
  consts/experiences.js
  pages/index.js
  public/translations/en.json
  public/translations/vn.json
  styles/blocks/services.sass
  styles/helpers/base.sass
  views/components/Experiences.js
  views/components/Service.js
  views/components/__test__/Experiences.spec.tsx
  views/components/__test__/__snapshots__/Experiences.spec.tsx.snap
  views/components/experiences/Bold.js
  views/components/experiences/Container.js
  views/components/experiences/Description.js
  views/components/experiences/ExpIcon.js
  views/components/experiences/Header.js
  views/components/experiences/Item.js
  views/components/experiences/List.js
  views/components/experiences/Title.js
  views/theme.js
Labels: enhancement

#50 Add error
  pages/_app.js
  pages/_error.js
  public/images/oops.jpg
  views/components/Error.js
  views/components/ErrorBoundary.js
  views/components/__test__/Error.spec.tsx
  views/components/__test__/__snapshots__/Error.spec.tsx.snap
  views/components/error/General.js
  views/components/error/InternalServer.js
  views/components/error/Layout.js
  views/components/error/NotFound.js
  views/components/error/layout/Button.js
  views/components/error/layout/Description.js
  views/components/error/layout/Header.js
  views/components/error/layout/Title.js
Labels: enhancement

#57 Fix bug language selected
  views/components/nav/NavHeader.js
  views/components/nav/NavLang.js
  views/components/nav/NavLink.js
  views/components/nav/__test__/__snapshots__/NavHeader.spec.tsx.snap
  views/components/nav/__test__/__snapshots__/NavLink.spec.tsx.snap
Labels: bug

#45 Update Certification.js
  consts/certification.js
  pages/index.js
  public/translations/en.json
  public/translations/vn.json
  styles/blocks/process.sass
  views/components/Certification.js
  views/components/Experiences.js
  views/components/__test__/__snapshots__/Experiences.spec.tsx.snap
  views/components/certification/Cert.js
  views/components/certification/CertIcon.js
  views/components/certification/Info.js
  views/components/certification/Item.js
  views/components/certification/Title.js
  views/components/common/section/Container.js
  views/components/common/section/Header.js
  views/theme.js
Labels: enhancement

#63 Add Project component
  pages/index.js
  public/images/projects/2048.jpg
  public/images/projects/8.jpg
  public/images/projects/anco.jpg
  public/images/projects/book-reader.jpg
  public/images/projects/brand360.jpg
  public/images/projects/taman.jpg
  public/translations/en.json
  public/translations/vn.json
  styles/blocks/projects.sass
  styles/helpers/base.sass
  views/components/Project.js
  views/components/__test__/Project.spec.tsx
  views/components/__test__/__snapshots__/Project.spec.tsx.snap
  views/components/common/section/Container.js
  views/components/project/Caption.js
  views/components/project/Content.js
  views/components/project/Item.js
  views/theme.js
Labels: enhancement

#67 Add test Certification
  views/components/__test__/Certification.spec.tsx
  views/components/__test__/__snapshots__/Certification.spec.tsx.snap
Labels: enhancement

#70 Fix hash links nav bar
  views/components/Project.js
  views/components/__test__/__snapshots__/Certification.spec.tsx.snap
  views/components/__test__/__snapshots__/Experiences.spec.tsx.snap
  views/components/__test__/__snapshots__/Project.spec.tsx.snap
  views/components/common/section/Container.js
Labels: bug

#75 Swap Project and Certification
  pages/index.js
Labels: bug

#68 Add bootstrap
  consts/experiences.js
  next.config.js
  package.json
  pages/_app.js
  styles/blocks/about.sass
  styles/blocks/header.sass
  styles/blocks/projects.sass
  styles/blocks/services.sass
  styles/blocks/testimonials.sass
  styles/globalStyle.sass
  styles/helpers/base.sass
  views/components/About.js
  views/components/Certification.js
  views/components/Contact.js
  views/components/Experiences.js
  views/components/Home.js
  views/components/WhyMe.js
  views/components/__test__/__snapshots__/About.spec.tsx.snap
  views/components/__test__/__snapshots__/Certification.spec.tsx.snap
  views/components/__test__/__snapshots__/Contact.spec.tsx.snap
  views/components/__test__/__snapshots__/Experiences.spec.tsx.snap
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
  views/components/__test__/__snapshots__/Project.spec.tsx.snap
  views/components/__test__/__snapshots__/WhyMe.spec.tsx.snap
  views/components/common/container/MobileContainer.js
  views/components/common/section/Container.js
  views/components/contact/Content.js
  views/components/contact/Header.js
  views/components/contact/Map.js
  views/components/experiences/List.js
  views/components/nav/NavContent.js
  views/components/nav/NavHeader.js
  views/components/nav/NavItem.js
  views/components/nav/NavLang.js
  views/components/nav/NavLink.js
  views/components/nav/NavLogo.js
  views/components/nav/__test__/__snapshots__/NavContent.spec.tsx.snap
  views/components/nav/__test__/__snapshots__/NavHeader.spec.tsx.snap
  views/components/nav/__test__/__snapshots__/NavLang.spec.tsx.snap
  views/components/nav/__test__/__snapshots__/NavLink.spec.tsx.snap
  views/components/project/Caption.js
  views/components/project/Content.js
  views/components/project/Item.js
  yarn.lock
Labels: enhancement

#79 Create LICENSE
  LICENSE
Labels: documentation

#82 Href link improve
  package.json
  pages/_app.js
  styles/helpers/base.sass
  utils/helpers.js
  views/components/About.js
  views/components/Certification.js
  views/components/Contact.js
  views/components/Experiences.js
  views/components/Home.js
  views/components/Project.js
  views/components/__test__/__snapshots__/About.spec.tsx.snap
  views/components/__test__/__snapshots__/Certification.spec.tsx.snap
  views/components/__test__/__snapshots__/Contact.spec.tsx.snap
  views/components/__test__/__snapshots__/Experiences.spec.tsx.snap
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
  views/components/__test__/__snapshots__/Project.spec.tsx.snap
  views/components/common/Anchor.js
  views/components/common/section/Container.js
  views/components/nav/NavContent.js
  views/components/nav/__test__/NavContent.spec.tsx
  views/components/project/Caption.js
  yarn.lock
Labels: bug, enhancement

#84 Update circle CI run test on single thread
  .circleci/config.yml
Labels: bug

#85 Swap Project and Certification pos on Navbar
  consts/pages.js
  views/components/nav/__test__/__snapshots__/NavContent.spec.tsx.snap
Labels: bug

#86 Adding animation
  package.json
  pages/index.js
  utils/helpers.js
  views/components/SlideIterator.js
  views/components/__test__/SlideIterator.spec.tsx
  views/components/__test__/__snapshots__/SlideIterator.spec.tsx.snap
  views/components/nav/NavContent.js
  yarn.lock
Labels: enhancement

#90 Fix extra space on mobile device
  views/components/Navbar.js
  views/components/WhyMe.js
  views/components/__test__/__snapshots__/WhyMe.spec.tsx.snap
  views/components/nav/NavHeader.js
  views/components/nav/__test__/__snapshots__/NavHeader.spec.tsx.snap
  views/theme.js
Labels: bug

#88 Add bootstrap for Certification
  consts/certification.js
  public/translations/en.json
  public/translations/vn.json
  styles/blocks/process.sass
  styles/globalStyle.sass
  views/components/Certification.js
  views/components/__test__/__snapshots__/Certification.spec.tsx.snap
  views/components/certification/Cert.js
  views/components/certification/CertIcon.js
  views/components/certification/CertInfo.js
  views/components/certification/CertItem.js
  views/components/certification/Info.js
  views/components/certification/Item.js
Labels: enhancement

#95 Commit Theme Selector with Xmax and New year theme
  consts/experiences.js
  pages/_app.js
  public/images/christmas/bg-christmas.jpg
  public/images/christmas/bg-pattern-snow.png
  public/images/map.jpg
  public/images/oops.jpg
  public/translations/en.json
  public/translations/vn.json
  styles/globalStyle.sass
  styles/helpers/base.sass
  styles/helpers/variables.sass
  styles/vendor/gs.sass
  styles/vendor/mixins.sass
  theme/christMasTheme.js
  theme/newYearTheme.js
  theme/theme.js
  utils/helpers.js
  utils/withThemeProviders.js
  views/components/__test__/__snapshots__/Experiences.spec.tsx.snap
  views/original-components/Loading.js
  views/theme/ThemeProviderSelector.js
Labels: enhancement

#100 Fix bugs from #96 #97 #99
  public/translations/en.json
  public/translations/vn.json
  views/components/Certification.js
  views/components/Contact.js
  views/components/__test__/__snapshots__/Certification.spec.tsx.snap
  views/components/__test__/__snapshots__/Contact.spec.tsx.snap
  views/components/contact/Socials.js
Labels: bug

#101 Improve code coverage of Socials component
  views/components/__test__/__snapshots__/Contact.spec.tsx.snap
  views/components/contact/Socials.js
  views/components/contact/__test__/Socials.spec.tsx
Labels: enhancement

#105 Add new year theme
  public/images/newyear/bg-newyear.jpg
  public/images/newyear/bg-pattern.jpg
  theme/christMasTheme.js
  theme/newYearTheme.js
  theme/theme.js
  views/components/About.js
  views/components/Home.js
  views/components/__test__/__snapshots__/About.spec.tsx.snap
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
  views/theme/__test__/__snapshots__/GlobalStyleCss.spec.tsx.snap
  views/theme/__test__/__snapshots__/ThemeProviderSelector.spec.tsx.snap
Labels: enhancement

#107 Fixing Head Meta data
  public/images/cover.png
  public/images/map.jpg
  public/images/map.png
  views/components/Head.js
  views/components/__test__/__snapshots__/Contact.spec.tsx.snap
  views/components/contact/Map.js
Labels: enhancement

#109 Change og:image
  public/images/cover.png
  views/components/Head.js
Labels: enhancement

#113 Move head inside _document.js
  pages/_app.js
  pages/_document.js
  pages/index.js
  views/components/Head.js
  views/components/__test__/Head.spec.tsx
  views/components/__test__/__snapshots__/Head.spec.tsx.snap
Labels: bug

#119 Adding Tet theme
  public/images/tet/bg-pattern.jpg
  public/images/tet/bg-tet.jpg
  theme/tetTheme.js
  utils/__test__/helpers.spec.tsx
  utils/helpers.js
  views/theme/ThemeProviderSelector.js
  views/theme/__test__/ThemeProviderSelector.spec.tsx
  views/theme/__test__/__snapshots__/ThemeProviderSelector.spec.tsx.snap
Labels: enhancement

#121 Refractor Head
  pages/_document.js
  pages/index.js
  views/components/Head.js
  views/components/__test__/Head.spec.tsx
  views/components/__test__/__snapshots__/Head.spec.tsx.snap
Labels: enhancement

#123 Add type effect
  consts/typist.js
  public/translations/en.json
  public/translations/vn.json
  views/components/Home.js
  views/components/__test__/Home.spec.tsx
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
  views/components/common/Typist.js
  views/components/common/__test__/Typist.spec.tsx
  views/components/common/__test__/__snapshots__/Typist.spec.tsx.snap
  yarn.lock
Labels: enhancement

#139 [135] Adding github link to Logo
  views/components/__test__/__snapshots__/Navbar.spec.tsx.snap
  views/components/nav/NavLogo.js
  views/components/nav/__test__/__snapshots__/NavContent.spec.tsx.snap
  views/components/nav/__test__/__snapshots__/NavLogo.spec.tsx.snap
Labels: enhancement

#141 Reduce Style Jsx noise by babel-test
  .babelrc
  views/components/__test__/__snapshots__/Home.spec.tsx.snap
  views/components/common/__test__/__snapshots__/Typist.spec.tsx.snap
  views/original-components/__test__/__snapshots__/Loading.spec.tsx.snap
  views/theme/__test__/__snapshots__/GlobalStyleCss.spec.tsx.snap
Labels: enhancement

#142 Adjust new year time
  utils/__test__/helpers.spec.tsx
  utils/helpers.js
Labels: enhancement
